// Package grpc is gRPC served by fib's engine: unary and streaming calls both
// ways, metadata, deadlines, cancellation, status codes, interceptors,
// compression and TLS, over an HTTP/2 transport of its own that speaks to
// google.golang.org/grpc clients and servers.
//
// # Generated code
//
// The package has the names that code generated by protoc-gen-go-grpc uses,
// so a service's generated _grpc.pb.go works here once its imports of
// google.golang.org/grpc, google.golang.org/grpc/codes and
// google.golang.org/grpc/status name github.com/lesismal/fib/grpc and its
// codes and status packages instead:
//
//	sed -i 's#google.golang.org/grpc#github.com/lesismal/fib/grpc#' foo_grpc.pb.go
//
// This module depends on nothing outside the standard library, so it cannot
// encode messages of google.golang.org/protobuf itself; RegisterCodec shows
// the codec a program registers for them. Messages that encode themselves,
// as vtprotobuf's and gogo/protobuf's do, need none, and the "json" codec
// serves calls whose content subtype is json.
//
// # Servers
//
// A Server is a fib.Handler serving HTTP/2 with prior knowledge (h2c):
//
//	server := grpc.NewServer()
//	pb.RegisterGreeterServer(server, &greeter{})
//	engine, err := fib.Bind(config, server)
//
// For TLS, wrap it: fibtls.NewServer(grpc.ConfigureTLS(tlsConfig), server).
// Serve and ServeTLS make the engine themselves.
//
// To serve gRPC on the same port as package http's HTTP, route the
// service's paths to the Server, whose ServeHTTP serves the calls that
// package http's HTTP/2 brings it; see ServeHTTP for what that can serve.
//
// Every call's handler runs on a task pool, never on the engine worker that
// reads the connection, so a handler that blocks holds up only its own call.
// The pool is fib.Engine.HandlerPool of the connection's engine, the one
// fib's HTTP/2 and HTTP/3 run their handlers on, unless the TaskPool option
// names another. A unary call goes to the pool once its request has arrived
// whole; a streaming call as soon as it opens.
//
// # Clients
//
// A ClientConn connects to one server when its first call needs a
// connection, and again after it loses one:
//
//	conn, err := grpc.NewClient("127.0.0.1:50051", grpc.WithEngine(engine))
//	client := pb.NewGreeterClient(conn)
//
// Close a ClientConn before closing its engine, which ends its connections
// without a word to the calls on them.
//
// # Not implemented
//
// Name resolution and load balancing beyond one host:port target, retries
// and service config, keepalive pings, channelz, the health, reflection and
// binary log services, and the decoding of grpc-status-details-bin, which
// travels as bytes.
package grpc
