//go:build linux || darwin || windows

package grpc

import (
	"context"

	"github.com/lesismal/fib/grpc/metadata"
)

// The SupportPackageIsVersion constants are what code generated by
// protoc-gen-go-grpc checks the package against.
const (
	SupportPackageIsVersion7 = true
	SupportPackageIsVersion8 = true
	SupportPackageIsVersion9 = true
)

// MethodDesc describes a unary method of a service.
type MethodDesc struct {
	MethodName string
	Handler    MethodHandler
}

// MethodHandler is what generated code makes of a unary method: it decodes
// the request with dec and calls the method, through interceptor if there is
// one.
type MethodHandler func(srv any, ctx context.Context, dec func(any) error, interceptor UnaryServerInterceptor) (any, error)

// StreamHandler serves a streaming method.
type StreamHandler func(srv any, stream ServerStream) error

// StreamDesc describes a streaming method.
type StreamDesc struct {
	StreamName    string
	Handler       StreamHandler
	ServerStreams bool
	ClientStreams bool
}

// ServiceDesc describes a service, as generated code declares it.
type ServiceDesc struct {
	ServiceName string
	// HandlerType is a pointer to the service's interface, which the
	// implementation registered must satisfy.
	HandlerType any
	Methods     []MethodDesc
	Streams     []StreamDesc
	Metadata    any
}

// ServiceRegistrar registers services, as a Server does.
type ServiceRegistrar interface {
	RegisterService(desc *ServiceDesc, impl any)
}

// ServiceInfo describes a registered service.
type ServiceInfo struct {
	Methods  []MethodInfo
	Metadata any
}

// MethodInfo describes a method of a registered service.
type MethodInfo struct {
	Name           string
	IsClientStream bool
	IsServerStream bool
}

// UnaryServerInfo is what a unary interceptor is told of the call.
type UnaryServerInfo struct {
	Server     any
	FullMethod string
}

// UnaryHandler is the rest of a unary call: what an interceptor calls.
type UnaryHandler func(ctx context.Context, req any) (any, error)

// UnaryServerInterceptor intercepts a unary call on the server.
type UnaryServerInterceptor func(ctx context.Context, req any, info *UnaryServerInfo, handler UnaryHandler) (resp any, err error)

// StreamServerInfo is what a stream interceptor is told of the call.
type StreamServerInfo struct {
	FullMethod     string
	IsClientStream bool
	IsServerStream bool
}

// StreamServerInterceptor intercepts a streaming call on the server.
type StreamServerInterceptor func(srv any, ss ServerStream, info *StreamServerInfo, handler StreamHandler) error

// UnaryInvoker is the rest of a unary call on the client.
type UnaryInvoker func(ctx context.Context, method string, req, reply any, cc *ClientConn, opts ...CallOption) error

// UnaryClientInterceptor intercepts a unary call on the client.
type UnaryClientInterceptor func(ctx context.Context, method string, req, reply any, cc *ClientConn, invoker UnaryInvoker, opts ...CallOption) error

// Streamer opens the stream of a call on the client.
type Streamer func(ctx context.Context, desc *StreamDesc, cc *ClientConn, method string, opts ...CallOption) (ClientStream, error)

// StreamClientInterceptor intercepts the opening of a stream on the client.
type StreamClientInterceptor func(ctx context.Context, desc *StreamDesc, cc *ClientConn, method string, streamer Streamer, opts ...CallOption) (ClientStream, error)

// ClientConnInterface is what generated clients call through, as a
// ClientConn does.
type ClientConnInterface interface {
	Invoke(ctx context.Context, method string, args any, reply any, opts ...CallOption) error
	NewStream(ctx context.Context, desc *StreamDesc, method string, opts ...CallOption) (ClientStream, error)
}

// ServerStream is the server's side of a streaming call.
type ServerStream interface {
	// SetHeader sets header metadata to send, merged with what was set
	// before, until the header is sent.
	SetHeader(metadata.MD) error
	// SendHeader sends the header, with md merged in. It is sent at the
	// latest with the first message or the status.
	SendHeader(metadata.MD) error
	// SetTrailer sets trailer metadata, sent with the status.
	SetTrailer(metadata.MD)
	// Context is the call's context.
	Context() context.Context
	// SendMsg sends a message.
	SendMsg(m any) error
	// RecvMsg receives a message into m, returning io.EOF once the client
	// has sent all of them.
	RecvMsg(m any) error
}

// ClientStream is the client's side of a streaming call.
type ClientStream interface {
	// Header waits for the server's header metadata.
	Header() (metadata.MD, error)
	// Trailer returns the server's trailer metadata, once RecvMsg has
	// returned an error, io.EOF included.
	Trailer() metadata.MD
	// CloseSend tells the server that nothing more will be sent.
	CloseSend() error
	// Context is the call's context.
	Context() context.Context
	// SendMsg sends a message. It returns io.EOF if the call has ended,
	// whose status RecvMsg then gives.
	SendMsg(m any) error
	// RecvMsg receives a message into m. It returns io.EOF when the call
	// ended with codes.OK and no more messages, and the status otherwise.
	RecvMsg(m any) error
}

// ServerStreamingClient is the client of a call whose server streams.
type ServerStreamingClient[Res any] interface {
	Recv() (*Res, error)
	ClientStream
}

// ServerStreamingServer is the server of a call whose server streams.
type ServerStreamingServer[Res any] interface {
	Send(*Res) error
	ServerStream
}

// ClientStreamingClient is the client of a call whose client streams.
type ClientStreamingClient[Req any, Res any] interface {
	Send(*Req) error
	CloseAndRecv() (*Res, error)
	ClientStream
}

// ClientStreamingServer is the server of a call whose client streams.
type ClientStreamingServer[Req any, Res any] interface {
	Recv() (*Req, error)
	SendAndClose(*Res) error
	ServerStream
}

// BidiStreamingClient is the client of a call streaming both ways.
type BidiStreamingClient[Req any, Res any] interface {
	Send(*Req) error
	Recv() (*Res, error)
	ClientStream
}

// BidiStreamingServer is the server of a call streaming both ways.
type BidiStreamingServer[Req any, Res any] interface {
	Recv() (*Req, error)
	Send(*Res) error
	ServerStream
}

// GenericClientStream gives a ClientStream the typed methods of the
// streaming client interfaces.
type GenericClientStream[Req any, Res any] struct {
	ClientStream
}

func (x *GenericClientStream[Req, Res]) Send(m *Req) error { return x.ClientStream.SendMsg(m) }

func (x *GenericClientStream[Req, Res]) Recv() (*Res, error) {
	m := new(Res)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (x *GenericClientStream[Req, Res]) CloseAndRecv() (*Res, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Res)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GenericServerStream gives a ServerStream the typed methods of the
// streaming server interfaces.
type GenericServerStream[Req any, Res any] struct {
	ServerStream
}

func (x *GenericServerStream[Req, Res]) Send(m *Res) error { return x.ServerStream.SendMsg(m) }

func (x *GenericServerStream[Req, Res]) SendAndClose(m *Res) error { return x.ServerStream.SendMsg(m) }

func (x *GenericServerStream[Req, Res]) Recv() (*Req, error) {
	m := new(Req)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChainUnaryServer combines interceptors into one, the first outermost.
func chainUnaryServer(interceptors []UnaryServerInterceptor) UnaryServerInterceptor {
	switch len(interceptors) {
	case 0:
		return nil
	case 1:
		return interceptors[0]
	}
	return func(ctx context.Context, req any, info *UnaryServerInfo, handler UnaryHandler) (any, error) {
		return interceptors[0](ctx, req, info, unaryChainHandler(interceptors, 0, info, handler))
	}
}

func unaryChainHandler(interceptors []UnaryServerInterceptor, curr int, info *UnaryServerInfo, final UnaryHandler) UnaryHandler {
	if curr == len(interceptors)-1 {
		return final
	}
	return func(ctx context.Context, req any) (any, error) {
		return interceptors[curr+1](ctx, req, info, unaryChainHandler(interceptors, curr+1, info, final))
	}
}

func chainStreamServer(interceptors []StreamServerInterceptor) StreamServerInterceptor {
	switch len(interceptors) {
	case 0:
		return nil
	case 1:
		return interceptors[0]
	}
	return func(srv any, ss ServerStream, info *StreamServerInfo, handler StreamHandler) error {
		return interceptors[0](srv, ss, info, streamChainHandler(interceptors, 0, info, handler))
	}
}

func streamChainHandler(interceptors []StreamServerInterceptor, curr int, info *StreamServerInfo, final StreamHandler) StreamHandler {
	if curr == len(interceptors)-1 {
		return final
	}
	return func(srv any, ss ServerStream) error {
		return interceptors[curr+1](srv, ss, info, streamChainHandler(interceptors, curr+1, info, final))
	}
}

func chainUnaryClient(interceptors []UnaryClientInterceptor) UnaryClientInterceptor {
	switch len(interceptors) {
	case 0:
		return nil
	case 1:
		return interceptors[0]
	}
	return func(ctx context.Context, method string, req, reply any, cc *ClientConn, invoker UnaryInvoker, opts ...CallOption) error {
		return interceptors[0](ctx, method, req, reply, cc, unaryClientChain(interceptors, 0, invoker), opts...)
	}
}

func unaryClientChain(interceptors []UnaryClientInterceptor, curr int, final UnaryInvoker) UnaryInvoker {
	if curr == len(interceptors)-1 {
		return final
	}
	return func(ctx context.Context, method string, req, reply any, cc *ClientConn, opts ...CallOption) error {
		return interceptors[curr+1](ctx, method, req, reply, cc, unaryClientChain(interceptors, curr+1, final), opts...)
	}
}

func chainStreamClient(interceptors []StreamClientInterceptor) StreamClientInterceptor {
	switch len(interceptors) {
	case 0:
		return nil
	case 1:
		return interceptors[0]
	}
	return func(ctx context.Context, desc *StreamDesc, cc *ClientConn, method string, streamer Streamer, opts ...CallOption) (ClientStream, error) {
		return interceptors[0](ctx, desc, cc, method, streamClientChain(interceptors, 0, streamer), opts...)
	}
}

func streamClientChain(interceptors []StreamClientInterceptor, curr int, final Streamer) Streamer {
	if curr == len(interceptors)-1 {
		return final
	}
	return func(ctx context.Context, desc *StreamDesc, cc *ClientConn, method string, opts ...CallOption) (ClientStream, error) {
		return interceptors[curr+1](ctx, desc, cc, method, streamClientChain(interceptors, curr+1, final), opts...)
	}
}
